
  <div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<?php echo $this->url('supplier-product'); ?>">Product</a>
      </li>
      <li class="breadcrumb-item active">Add Product</li>
    </ol>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>
     <h1>Add Product</h1>
     <hr>
    <div class="card mb-3">
      <div class="card-body">
        <?php
        $form->setAttribute('action', $this->url('supplier-product', ['action' => 'add',]));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
          <?= $this->formLabel($form->get('name')) ?>
          <?= $this->formElement($form->get('name')) ?>
          <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
          <?= $this->formLabel($form->get('description')) ?>
          <?= $this->formElement($form->get('description')) ?>
          <?= $this->formElementErrors()->render($form->get('description'), ['class' => 'help-block']) ?>
        </div>
        <div class="row">
          <div class="col-md-3">
            <div class="form-group">
              <?= $this->formLabel($form->get('stock')) ?>
              <?= $this->formElement($form->get('stock')) ?>
              <?= $this->formElementErrors()->render($form->get('stock'), ['class' => 'help-block']) ?>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <?= $this->formLabel($form->get('price')) ?>
              <?= $this->formElement($form->get('price')) ?>
              <?= $this->formElementErrors()->render($form->get('price'), ['class' => 'help-block']) ?>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <?= $this->formLabel($form->get('discount_type')) ?>
              <?= $this->formElement($form->get('discount_type')) ?>
              <?= $this->formElementErrors()->render($form->get('discount_type'), ['class' => 'help-block']) ?>
            </div>
          </div>
          <div class="col-md-3">
            <div class="form-group">
              <?= $this->formLabel($form->get('discount')) ?>
              <?= $this->formElement($form->get('discount')) ?>
              <?= $this->formElementErrors()->render($form->get('discount'), ['class' => 'help-block']) ?>
            </div>
          </div>
        </div>
        <div class="form-group">
          <?= $this->formLabel($form->get('brand_id')) ?>
          <?= $this->formElement($form->get('brand_id')) ?>
          <?= $this->formElementErrors()->render($form->get('brand_id'), ['class' => 'help-block']) ?>
        </div>
        <div class="form-group">
          <?= $this->formLabel($form->get('category_id')) ?>
          <?= $this->formElement($form->get('category_id')) ?>
          <?= $this->formElementErrors()->render($form->get('name'), ['class' => 'help-block']) ?>
        </div>

        <h3>Photos</h3>

        <div class="form-group">
          <?= $this->formLabel($form->get('photo1')) ?>
          <?= $this->formFile($form->get('photo1')) ?>
          <?= $this->formElementErrors()->render($form->get('photo1'), ['class' => 'help-block']) ?>
          <ul class="help-block">
            <li>File Types: jpg</li>
            <li>Dimension at least: 700x400</li>
          </ul>
        </div>
        <div class="form-group">
          <?= $this->formLabel($form->get('photo2')) ?>
          <?= $this->formFile($form->get('photo2')) ?>
          <?= $this->formElementErrors()->render($form->get('photo2'), ['class' => 'help-block']) ?>
          <ul class="help-block">
            <li>File Types: jpg</li>
            <li>Dimension at least: 700x400</li>
          </ul>
        </div>
        <div class="form-group">
          <?= $this->formLabel($form->get('photo3')) ?>
          <?= $this->formFile($form->get('photo3')) ?>
          <?= $this->formElementErrors()->render($form->get('photo3'), ['class' => 'help-block']) ?>
          <ul class="help-block">
            <li>File Types: jpg</li>
            <li>Dimension at least: 700x400</li>
          </ul>
        </div>

        <h3>VR/Panorama</h3>

        <div class="form-group">
          <?= $this->formLabel($form->get('panorama')) ?>
          <?= $this->formFile($form->get('panorama')) ?>
          <?= $this->formElementErrors()->render($form->get('panorama'), ['class' => 'help-block']) ?>
          <ul class="help-block">
            <li>File Types: jpg</li>
            <li>Dimension at least: 6000x3000</li>
          </ul>
        </div>

        <?php echo $this->formSubmit($form->get('submit')); ?>
        <a href="<?php echo $this->url('supplier-product'); ?>" class="btn btn-secondary">Cancel</a>
        <?php echo $this->form()->closeTag();?>
      </div>

    </div>

  </div>
  <!-- /.container-fluid -->
