
  <div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<?php echo $this->url('supplier-product'); ?>">Product</a>
      </li>
      <li class="breadcrumb-item active">Overview</li>
    </ol>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>

    <div class="card mb-3">
      <div class="card-header">
        <?php
        $form->setAttribute('action', $this->url('supplier-product', ['action' => 'search',]));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="form-row">
          <div class="col"><?= $this->formElement($form->get('category_id')) ?></div>
          <div class="col"><?= $this->formElement($form->get('brand_id')) ?></div>
          <div class="col"><?= $this->formElement($form->get('keyword')) ?></div>
          <?php echo $this->formSubmit($form->get('submit')); ?>
          <div class="col"><a href="<?php echo $this->url('supplier-product', ['action' => 'add',]); ?>" class="btn btn-secondary">Add</a></div>
        </div>
        <?php echo $this->form()->closeTag();?>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <form id="frmSearch" method="post">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th>Brand</th>
                  <th>Name</th>
                  <th style="width:10%">QR Code</th>
                  <th style="width:3%">Edit</th>
                  <th style="width:3%">Delete</th>
                </tr>
              </thead>
              <tbody>
                <?php if (count($this->paginator)): ?>
                  <?php foreach ($this->paginator as $row): ?>
                <tr>
                  <td><?php echo $this->escapeHtml($row['brand']); ?></td>
                  <td><?php echo $this->escapeHtml($row['name']); ?></td>
                  <td><a href="<?php echo $this->url('supplier-product', ['action' => 'qrcode', 'id' => $row['id'],]); ?>">QR Code</a></td>
                  <td><a href="<?php echo $this->url('supplier-product', ['action' => 'edit', 'id' => $row['id'],]); ?>">Edit</a></td>
                  <td><a class="delete" data-id="<?php echo $this->escapeHtml($row['name']); ?>" href="<?php echo $this->url('supplier-product', ['action' => 'delete', 'id' => $row['id'],]); ?>">Delete</a></td>
                </tr>
                  <?php endforeach; ?>
                <?php endif; ?>
              </tbody>
            </table>
          </form>
        </div>
      </div>
      <div class="card-footer small text-muted">
        <?= $this->paginationControl(
            $this->paginator,
            'Sliding',
            'partial/supplier-product/paginator.phtml',
            [
              'route' => 'supplier-product',
            ]
        ) ?>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->


<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalTitle">Delete Brand</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="deleteButton">Delete</button>
      </div>
    </div>
  </div>
</div>

<!-- Delete Selected Modal -->
<div class="modal fade" id="deleteSelectedModal" tabindex="-1" role="dialog" aria-labelledby="deleteSelectedModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteSelectedModalTitle">Delete Selected cBrand</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete selected category?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="deleteSelectedButton">Delete</button>
      </div>
    </div>
  </div>
</div>

<?php $this->headScript()->appendFile('/js/checkbox.js')->appendFile('/js/delete.js'); ?>
