  <div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<?php echo $this->url('supplier-category'); ?>">Category</a>
      </li>
      <li class="breadcrumb-item active">Edit Category</li>
    </ol>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>
     <h1>Edit Category</h1>
     <hr>
    <div class="card mb-3">
      <div class="card-body">
        <?php
        $form->setAttribute('action', $this->url('supplier-category', ['action' => 'edit', 'id' => $this->category->getId()]));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="form-group">
          <?= $this->formLabel($form->get('category')) ?>
          <?= $this->formElement($form->get('category')) ?>
          <?= $this->formElementErrors()->render($form->get('category'), ['class' => 'help-block']) ?>
        </div>
        <?php echo $this->formSubmit($form->get('submit')); ?>
        <a href="<?php echo $this->url('supplier-category'); ?>" class="btn btn-secondary">Cancel</a>
        <?php echo $this->form()->closeTag();?>
      </div>

    </div>

  </div>
  <!-- /.container-fluid -->
