
  <div class="container-fluid">

    <!-- Breadcrumbs-->
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="<?php echo $this->url('admin-user'); ?>">User</a>
      </li>
      <li class="breadcrumb-item active">Overview</li>
    </ol>

    <?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        ')
        ->setMessageSeparatorString('')
        ->setMessageCloseString('</div>');

    echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
    echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
    echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
    echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
     ?>

    <div class="card mb-3">
      <div class="card-header">
        <?php
        $form->setAttribute('action', $this->url('admin-user', ['action' => 'search',]));
        $form->prepare();
        echo $this->form()->openTag($form);
        ?>
        <div class="form-row">
          <div class="col"><?= $this->formElement($form->get('first_name_keyword')) ?></div>
          <div class="col"><?= $this->formElement($form->get('last_name_keyword')) ?></div>
          <div class="col"><?= $this->formElement($form->get('email_keyword')) ?></div>
          <div class="col"><?= $this->formSelect($form->get('role')) ?></div>
          <?php echo $this->formSubmit($form->get('submit')); ?>
          <div class="col"><a href="<?php echo $this->url('admin-user', ['action' => 'add',]); ?>" class="btn btn-secondary">Add</a></div>
        </div>
        <?php echo $this->form()->closeTag();?>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <form id="frmSearch" method="post">
            <table class="table table-bordered table-striped table-hover">
              <thead>
                <tr>
                  <th style="width:2%"><input type="checkbox" id="checkAll"/></th>
                  <th>First Name</th>
                  <th>Last Name</th>
                  <th>Email</th>
                  <th>Role</th>
                  <th style="width:3%">Edit</th>
                  <th style="width:3%">Delete</th>
                </tr>
              </thead>
              <tbody>
                <?php if (count($this->paginator)): ?>
                  <?php foreach ($this->paginator as $user): ?>
                <tr>
                  <td><?php if($this->identity()->id!=$user->getId()): ?><input type="checkbox" name="ids[]" value="<?php echo $this->escapeHtml($user->getId());?>"><?php endif; ?></td>
                  <td><?php echo $this->escapeHtml($user->getFirstName()); ?></td>
                  <td><?php echo $this->escapeHtml($user->getLastName()); ?></td>
                  <td><a href="mailto:<?php echo $this->escapeHtml($user->getEmail()); ?>"><?php echo $this->escapeHtml($user->getEmail()); ?></a></td>
                  <td><?php echo $this->escapeHtml($user->getRole()); ?></td>
                  <td><a href="<?php echo $this->url('admin-user', ['action' => 'edit', 'id' => $user->getId(),]); ?>">Edit</a></td>
                  <td><?php if($this->identity()->id!=$user->getId()): ?><a data-id="<?php echo $this->escapeHtml($user->getEmail()); ?>" class="delete" href="<?php echo $this->url('admin-user', ['action' => 'delete', 'id' => $user->getId(),]); ?>">Delete</a><?php endif; ?></td>
                </tr>
                  <?php endforeach; ?>
                <?php endif; ?>
              </tbody>
            </table>
            <button type="submit" class="delete-selected btn btn-danger">Delete Selected</button>
          </form>
        </div>
      </div>
      <div class="card-footer small text-muted">
        <?= $this->paginationControl(
            $this->paginator,
            'Sliding',
            'partial/admin-user/paginator.phtml',
            [
              'route' => 'admin-user',
            ]
        ) ?>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->


<!-- Delete Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalTitle">Delete User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="deleteButton">Delete</button>
      </div>
    </div>
  </div>
</div>

<!-- Delete Selected Modal -->
<div class="modal fade" id="deleteSelectedModal" tabindex="-1" role="dialog" aria-labelledby="deleteSelectedModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteSelectedModalTitle">Delete Selected User</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete selected users?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-danger" id="deleteSelectedButton">Delete</button>
      </div>
    </div>
  </div>
</div>

<?php $this->headScript()->appendFile('/js/checkbox.js')->appendFile('/js/delete.js'); ?>
