<!-- Page Heading/Breadcrumbs -->
<h1 class="mt-4 mb-3">Shipping
  <small>Address</small>
</h1>

<ol class="breadcrumb">
  <li class="breadcrumb-item">
    <a href="<?php echo $this->url('home'); ?>">Home</a>
  </li>
  <li class="breadcrumb-item active">Shipping Address</li>
</ol>

<div class="row">
      <div class="col-lg-8 mb-4">

        <?php
        $flash = $this->flashMessenger();
        $flash->setMessageOpenFormat('<div%s role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            ')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');

        echo $flash->render('error',   array('alert', 'alert-dismissible', 'alert-danger'));
        echo $flash->render('info',    array('alert', 'alert-dismissible', 'alert-info'));
        echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
        echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));
         ?>


        <div class="card card-register mx-auto">
          <div class="card-header">Shipping Address</div>
          <div class="card-body">
            <?php
            $form->setAttribute('action', $this->url('cart', array('action' => 'checkout')));
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

              <div class="form-group">
                <div class="form-row">
                  <div class="col-md-6">
                    <div class="form-label-group">
                      <?= $this->formElement($form->get('first_name')) ?>
                      <?= $this->formLabel($form->get('first_name')) ?>
                      <?= $this->formElementErrors()->render($form->get('first_name'), ['class' => 'help-block']) ?>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-label-group">
                      <?= $this->formElement($form->get('last_name')) ?>
                      <?= $this->formLabel($form->get('last_name')) ?>
                      <?= $this->formElementErrors()->render($form->get('last_name'), ['class' => 'help-block']) ?>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <?= $this->formElement($form->get('address')) ?>
                <?= $this->formLabel($form->get('address')) ?>
                <?= $this->formElementErrors()->render($form->get('address'), ['class' => 'help-block']) ?>
              </div>


              <div class="form-group">
                <div class="form-row">
                  <div class="col-md-4">
                    <div class="form-label-group">
                      <?= $this->formElement($form->get('city')) ?>
                      <?= $this->formLabel($form->get('city')) ?>
                      <?= $this->formElementErrors()->render($form->get('city'), ['class' => 'help-block']) ?>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-label-group">
                      <?= $this->formElement($form->get('country_id')) ?>
                      <?= $this->formLabel($form->get('country_id')) ?>
                      <?= $this->formElementErrors()->render($form->get('country_id'), ['class' => 'help-block']) ?>
                    </div>
                  </div>
                  <div class="col-md-4">
                    <div class="form-label-group">
                      <?= $this->formElement($form->get('zip')) ?>
                      <?= $this->formLabel($form->get('zip')) ?>
                      <?= $this->formElementErrors()->render($form->get('zip'), ['class' => 'help-block']) ?>
                    </div>
                  </div>
                </div>
              </div>

              <p>
                Shipping agreement, I agree to:
                <br><i class="fas fa-check-circle"></i> Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                <br><i class="fas fa-check-circle"></i> Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
              </p>
              <?php echo $this->formSubmit($form->get('submit')); ?>
            <?php echo $this->form()->closeTag();?>

          </div>
        </div>
      </div>
      <div class="col-lg-4 mb-4">
        <h3>Shipping Address Policy</h3>
        <p>
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
      </div>
    </div>
