<div class="list-group">
  <a href="<?php echo $this->url('member'); ?>" class="list-group-item <?php if($this->route=='member' && $this->action=='index'): ?>active<?php endif; ?>">Home</a>
  <a href="<?php echo $this->url('member', ['action' => 'bills']); ?>" class="list-group-item <?php if($this->route=='member' && ($this->action=='bills' || $this->action=='payments')): ?>active<?php endif; ?>">Bills/Payment</a>
  <a href="<?php echo $this->url('logout'); ?>" class="list-group-item">Logout</a>
</div>
