<?php if($this->categories): ?>
  <h3>Featured Categories</h3>
  <hr>
<div class="row">
  <?php foreach ($this->categories as $row): ?>
    <?php $url = $this->url('product', array('action' => 'index', 'search_by' => json_encode(array('search_category_id' => $row->getId(),)))); ?>
  <div class="col-lg-4 col-sm-6 portfolio-item">

    <div class="capslide_img_cont ic_container">
      <a href="<?php echo $url; ?>"><img src="/img/category/<?php echo $row->getId(); ?>/photo.jpg" class="card-img-top" alt=""/></a>
      <div class="overlay" style="display:none;"></div>
      <div class="ic_caption">
        <p class="ic_category">Category</p>
        <h3><?php echo $this->escapeHtml($row->getCategory()); ?></h3>
      </div>
    </div>

  </div>
  <?php endforeach; ?>
</div>
<?php endif; ?>

<hr>
<div class="row">
  <div class="col-lg-12">

    <br>
    <?php
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            "partial/home/paginator.phtml",
            array(
                'route' => 'product',
            'search_by' => $this->search_by,
            )
        );
      ?>
    <div class="row">
      <?php foreach ($paginator as $row): ?>
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
          <a href="<?php echo $this->url('product', array('action' => 'view', 'id' => $row['id'],)); ?>"><img class="card-img-top" src="/img/product/<?php echo $row->id; ?>/photo1-700x400.jpg" alt="<?php echo $this->escapeHtml($row['name']); ?>"></a>

          <div class="card-body">
            <div class="card-title">
              <h4><a href="<?php echo $this->url('product', array('action' => 'view', 'id' => $row['id'],)); ?>"><?php echo $this->escapeHtml($row['name']); ?></a></h4>
              <div class="row">
                <div class="col-md-6">
                  <small>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star"></i>
                      <i class="fas fa-star-half-alt"></i>
                      <i class="far fa-star"></i> (<?php echo rand(10,1000); ?>)
                    </small>
                </div>
                <div class="col-md-6 text-right">
                  <small><i class="far fa-heart"></i> (<?php echo rand(10,1000); ?>)
                </small>
                </div>
              </div>
            </div>
            <p class="card-text">
              <?php
              $maxLen = 100;
              $strLenDesc = strlen($row->description);
              if($strLenDesc > $maxLen): ?>
                <?php echo $this->escapehtml(substr($row->description, 0, $maxLen))
                      . " <a href=\"" . $this->url('product', array('action' => 'view', 'id' => $row->id,)) . "\">...</a>"; ?>
              <?php else: ?>
                <?php echo $this->escapehtml($row->description); ?>
            <?php endif; ?>
            </p>
            <?php
              switch($row->discount_type){
                case 'amount':
                  echo "<strong>SRP:</strong> <strike>₱" . number_format($row->price, 2, '.' , ',') . "</strike>";
                  echo "<small class=\"blink\"> less ₱" . number_format($row->discount, 2, '.' , ',') . "</small>";
                  $price = $row->price - $row->discount;
                  echo " <strong>₱" . number_format($price, 2, '.' , ',') . "</strong>";
                  break;
                case 'percentage':
                  echo "<strong>SRP:</strong> <strike>₱" . number_format($row->price, 2, '.' , ',') . "</strike>";
                  $discount = $row->price * ($row->discount/100);
                  echo "<small class=\"blink\"> less " . number_format($row->discount, 2, '.' , ',') . "%</small>";
                  $price = $row->price - $row->discount;
                  echo " <strong>₱" . number_format($price, 2, '.' , ',') . "</strong>";
                  break;
                default:
                  echo "<strong>SRP: ₱" . number_format($row->price, 2, '.' , ',') . "</strong>";
              }
            ?>

          </div>
          <div class="card-footer text-muted text-center">
            <a href="<?php echo $this->url('product', array('action' => 'view', 'id' => $row['id'],)); ?>" class="btn btn-primary">Add To Cart</a>
          </div>
        </div>
      </div>
      <?php endforeach; ?>
    </div>

    <?php
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            "partial/home/paginator.phtml",
            array(
                'route' => 'product',
            'search_by' => $this->search_by,
            )
        );
      ?>
  </div>
</div>
<hr>


<!-- /.row -->

<?php if($this->brands): ?>
<h3>Featured Brands</h3>
<hr>
<div class="row">
  <?php foreach ($this->brands as $row): ?>
    <?php $url = $this->url('product', array('action' => 'index', 'search_by' => json_encode(array('search_brand_id' => $row->getId(),)))); ?>
  <div class="col-lg-4 col-sm-6 portfolio-item">
    <div class="capslide_img_cont ic_container">
      <a href="<?php echo $url; ?>"><img src="/img/brand/<?php echo $row->getId(); ?>/logo.jpg" class="card-img-top" alt=""/></a>
      <div class="overlay" style="display:none;"></div>
      <div class="ic_caption">
        <p class="ic_category">Brand</p>
        <h3><?php echo $row->getBrand(); ?></h3>
      </div>
    </div>
  </div>
<?php endforeach; ?>
</div>
<hr>
<?php endif; ?>

<!-- Features Section -->
<div class="row">
  <div class="col-lg-6">
    <h2>Become A Partner</h2>
    <p>Choose the party that offers more than just that particular good or service</p>
    <ul>
      <li>Cost Optimization Sharing</li>
      <li>Transparent Communication</li>
      <li>Similar Goal(s)</li>
      <li>A company that is willing to go above and beyond in the short-term and long-term</li>
    </ul>
    <p>Business relationship based on mutual trust, openness, and shared risk and reward that yields a competitive advantage.</p>
  </div>
  <div class="col-lg-6">
    <img class="img-fluid rounded" src="/img/supplier.jpg" alt="">
  </div>
</div>

<hr>

<div class="row mb-4">
  <div class="col-md-8">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Molestias, expedita, saepe, vero rerum deleniti beatae veniam harum neque nemo praesentium cum alias asperiores commodi.</p>
  </div>
  <div class="col-md-4">
    <a class="btn btn-lg btn-secondary btn-block" href="<?php echo $this->url('supplier-registration'); ?>">Register as Partner</a>
  </div>
</div>
